In [26]:
import sys
import os
import pandas as pd
sys.path.append(os.path.abspath('../'))
from mcda.electre.concordance import *
from mcda.electre.discordance import *
from mcda.electre.credibility import *
from mcda.electre.outranking import *
from mcda.core.scales import QuantitativeScale, PreferenceDirection
from mcda.core.functions import Threshold

In [27]:
S1 = [0.48 , 81 , 38.5  , 2 , 380   , 5 , 4.28 , 5 , 10 , 2]
S2 = [0.44 , 74 , 37.8  , 2 , 311   , 5 , 4.05 , 4 , 9  , 2]
S3 = [0.44 , 74 , 28.7  , 1.5 , 286 , 3 , 3.94 , 5 , 8  , 3]
S4 = [0.58 , 215 , 13.3 , 2 , 480   , 4 , 4.70 , 5 , 11 , 2]
S5 = [0.44 , 48 , 29.4  , 1.5 , 391 , 5 , 4.05 , 5 , 10 , 2]
S6 = [0.48 , 90 , 29.4  , 2.5 , 361 , 4 , 4.37 , 5 , 10 , 3]
S7 = [0.48 , 110 , 37.8 , 2.5 , 600 , 5 , 4.68 , 5 , 10 , 3]
S8 = [0.41 , 33 , 13.9  , 90 , 300  , 5 , 3.73 , 1 , 6  , 2]
S9 = [0.58 , 104 , 23.8 , 2 , 443   , 5 , 4.47 , 5 , 8  , 5]
S10 = [0.41 , 70 , 11   , 240 , 363 , 3 , 3.63 , 4 , 8  , 2]
S11 = [0.58 , 109 , 14.4, 360 , 585 , 5 , 4.49 , 5 , 8  , 2]
S12 = [0.58 , 128 , 17  , 450 , 543 , 5 , 4.58 , 5 , 8  , 3]
columns = ["g1", "g2", "g3", "g4", "g5", "g6", "g7", "g8", "g9", "g10"]
indexes = ["S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "S9", "z10", "z11", "z12"]
data = pd.DataFrame([S1,S2,S3,S4,S5,S6,S7,S8,S9,S10,S11,S12], index=indexes, columns=columns)
data

       g1   g2    g3     g4   g5  g6    g7  g8  g9  g10
S1   0.48   81  38.5    2.0  380   5  4.28   5  10    2
S2   0.44   74  37.8    2.0  311   5  4.05   4   9    2
S3   0.44   74  28.7    1.5  286   3  3.94   5   8    3
S4   0.58  215  13.3    2.0  480   4  4.70   5  11    2
S5   0.44   48  29.4    1.5  391   5  4.05   5  10    2
S6   0.48   90  29.4    2.5  361   4  4.37   5  10    3
S7   0.48  110  37.8    2.5  600   5  4.68   5  10    3
S8   0.41   33  13.9   90.0  300   5  3.73   1   6    2
S9   0.58  104  23.8    2.0  443   5  4.47   5   8    5
z10  0.41   70  11.0  240.0  363   3  3.63   4   8    2
z11  0.58  109  14.4  360.0  585   5  4.49   5   8    2
z12  0.58  128  17.0  450.0  543   5  4.58   5   8    3

In [28]:
scales = pd.Series(
    [
        QuantitativeScale(0, 50000, PreferenceDirection.MIN),
        QuantitativeScale(0, 6000000),
        QuantitativeScale(0.0, 15000, PreferenceDirection.MIN),
        QuantitativeScale(0, 5000, PreferenceDirection.MIN),
        QuantitativeScale(0, 5000),
        QuantitativeScale(0, 5000),
        QuantitativeScale(0, 5000),
        QuantitativeScale(0, 5000),
        QuantitativeScale(0, 5000),
        QuantitativeScale(0, 50000),
    ],
    index=columns,
)


weights = pd.Series(
    [0.133, 0.176, 0.066, 0.1225, 0.1395, 0.084, 0.082, 0.082, 0.108, 0.007],
    index=columns,
)
q = pd.Series(
    [
        Threshold(0, 00.017),
        Threshold(0, 18.2),
        Threshold(0, 2.75),
        Threshold(0, 0),
        Threshold(0, 31.4),
        Threshold(0, 0),
        Threshold(0, 0),
        Threshold(0, 0),
        Threshold(0, 0),
        Threshold(0, 0),
    ],
    index=columns,
)
p = pd.Series(
    [
        Threshold(0, 0.042),
        Threshold(0, 45.5),
        Threshold(0, 6.875),
        Threshold(0, 1),
        Threshold(0, 78.5),
        Threshold(0, 1),
        Threshold(0, 1),
        Threshold(0, 1),
        Threshold(0, 1),
        Threshold(0, 1),
    ],
    index=columns,
)
rp = pd.Series(
    [
        Threshold(0, 0.085),
        Threshold(0, 91),
        None,
        Threshold(0, 60),
        Threshold(0, 157),
        None,
        None,
        None,
        Threshold(0, 4),
        None,
    ],
    index=columns,
)
omega = pd.Series(
    [1.5, 1.5, None, 1.2, 1.5, None, None, None, 1.2, None], index=columns
)
v = pd.Series(
    [
        Threshold(0, 0.136),
        Threshold(0, 145.6),
        None,
        Threshold(0, 120),
        Threshold(0, 150),
        None,
        None,
        None,
        Threshold(0, 4),
        None,
    ],
    index=columns,
)
wD = pd.Series([0.2, 0.2, 1, 0.2, 0.2, 1, 1, 1, 0.2, 1], index=columns)

In [29]:
rank_concordance = concordance_reinforced(data, scales, weights, q, p, rp, omega).round(3)
rank_concordance

,S1,S2,S3,S4,S5,S6,S7,S8,S9,z10,z11,z12
S1,1.000,0.878,0.743,0.509,0.750,0.920,0.751,0.806,0.800,0.806,0.738,0.621
S2,0.680,1.000,0.784,0.414,0.543,0.656,0.497,0.868,0.620,0.809,0.604,0.529
S3,0.641,0.799,1.000,0.404,0.659,0.644,0.493,0.786,0.640,0.736,0.594,0.525
S4,0.801,0.813,0.826,1.000,0.744,0.871,0.666,0.820,0.916,0.880,0.799,0.820
S5,0.886,0.950,0.943,0.491,1.000,0.813,0.626,0.868,0.696,0.844,0.617,0.604
S6,0.855,0.732,0.755,0.458,0.671,1.000,0.739,0.724,0.676,0.806,0.721,0.602
S7,0.943,0.828,0.709,0.613,0.709,0.938,1.000,0.818,0.874,0.818,0.940,0.940
S8,0.327,0.514,0.516,0.337,0.522,0.364,0.287,1.000,0.348,0.603,0.480,0.466
S9,0.759,0.759,0.806,0.615,0.698,0.759,0.602,0.806,1.000,0.806,0.798,0.755
z10,0.550,0.651,0.763,0.256,0.569,0.524,0.234,0.785,0.432,1.000,0.532,0.481
z11,0.660,0.660,0.755,0.576,0.660,0.654,0.614,0.761,0.870,0.751,1.000,0.981
z12,0.660,0.660,0.761,0.568,0.637,0.660,0.552,0.774,0.870,0.713,0.846,1.000

In [30]:
concordance(data, scales, weights, q, p).round(3)

,S1,S2,S3,S4,S5,S6,S7,S8,S9,z10,z11,z12
S1,1.000,0.878,0.743,0.476,0.750,0.920,0.751,0.801,0.787,0.801,0.714,0.587
S2,0.680,1.000,0.784,0.375,0.543,0.656,0.497,0.865,0.595,0.804,0.568,0.486
S3,0.641,0.799,1.000,0.364,0.659,0.644,0.493,0.781,0.616,0.730,0.557,0.482
S4,0.783,0.783,0.799,1.000,0.722,0.860,0.637,0.783,0.909,0.867,0.777,0.815
S5,0.886,0.950,0.943,0.457,1.000,0.813,0.626,0.865,0.676,0.840,0.582,0.568
S6,0.855,0.732,0.755,0.422,0.671,1.000,0.739,0.717,0.654,0.801,0.696,0.566
S7,0.939,0.816,0.689,0.587,0.689,0.934,1.000,0.801,0.866,0.801,0.934,0.934
S8,0.327,0.514,0.516,0.292,0.522,0.364,0.287,1.000,0.304,0.593,0.432,0.418
S9,0.759,0.759,0.806,0.615,0.698,0.759,0.602,0.801,1.000,0.801,0.793,0.749
z10,0.550,0.651,0.763,0.206,0.569,0.524,0.234,0.785,0.394,1.000,0.490,0.434
z11,0.637,0.637,0.738,0.576,0.637,0.630,0.614,0.744,0.870,0.734,1.000,0.980
z12,0.637,0.637,0.744,0.568,0.637,0.637,0.552,0.739,0.870,0.693,0.846,1.000

In [31]:
rank_discordance_marginal = discordance_marginals(alternatives_perform=data, scales=scales, preference_thresholds=p, veto_thresholds=v).round(3)
rank_discordance=discordance(rank_discordance_marginal, wD).round(3)
rank_discordance

,S1,S2,S3,S4,S5,S6,S7,S8,S9,z10,z11,z12
S1,0.000,0.000,0.000,0.039,0.000,0.000,0.033,0.010,0.000,0.010,0.033,0.034
S2,0.000,0.000,0.000,0.076,0.001,0.000,0.033,0.000,0.025,0.000,0.033,0.036
S3,0.018,0.000,0.000,0.087,0.023,0.011,0.044,0.000,0.033,0.000,0.033,0.036
S4,0.021,0.033,0.033,0.000,0.033,0.021,0.040,0.033,0.000,0.033,0.012,0.000
S5,0.000,0.000,0.000,0.038,0.000,0.000,0.039,0.000,0.003,0.000,0.038,0.045
S6,0.000,0.000,0.000,0.045,0.000,0.000,0.033,0.010,0.002,0.010,0.033,0.033
S7,0.000,0.000,0.000,0.020,0.000,0.000,0.000,0.010,0.000,0.010,0.000,0.000
S8,0.059,0.047,0.036,0.124,0.064,0.061,0.101,0.000,0.074,0.011,0.055,0.061
S9,0.032,0.033,0.033,0.044,0.044,0.032,0.065,0.033,0.000,0.033,0.030,0.010
z10,0.044,0.033,0.033,0.107,0.044,0.044,0.078,0.033,0.034,0.000,0.033,0.037
z11,0.065,0.067,0.067,0.076,0.078,0.065,0.065,0.067,0.033,0.067,0.000,0.000
z12,0.065,0.067,0.067,0.069,0.078,0.065,0.065,0.067,0.033,0.067,0.025,0.000

In [32]:
rank_non_discordance = non_discordance(rank_discordance, NonDiscordanceType.DC, rank_concordance).round(0)
rank_non_discordance

TypeError: Wrong marginal discordance indices type. Expected Series, but got float64 instead.

In [ ]:
rank_credibility_comprehensiv = credibility_comprehensive(rank_concordance, rank_non_discordance).round(3)
rank_credibility_comprehensiv

,S1,S2,S3,S4,S5,S6,S7,S8,S9,z10,z11,z12
S1,1.000,0.878,0.743,0.000,0.750,0.920,0.000,0.806,0.800,0.806,0.000,0.000
S2,0.680,1.000,0.784,0.000,0.543,0.656,0.000,0.868,0.620,0.809,0.000,0.000
S3,0.641,0.799,1.000,0.000,0.659,0.644,0.000,0.786,0.000,0.736,0.000,0.000
S4,0.801,0.000,0.000,1.000,0.000,0.871,0.666,0.000,0.916,0.000,0.799,0.820
S5,0.886,0.950,0.943,0.000,1.000,0.813,0.000,0.868,0.696,0.844,0.000,0.000
S6,0.855,0.732,0.755,0.000,0.671,1.000,0.000,0.724,0.676,0.806,0.000,0.000
S7,0.943,0.828,0.709,0.613,0.709,0.938,1.000,0.818,0.874,0.818,0.940,0.940
S8,0.000,0.000,0.516,0.000,0.000,0.000,0.000,1.000,0.000,0.603,0.000,0.000
S9,0.759,0.000,0.000,0.615,0.000,0.759,0.000,0.000,1.000,0.000,0.798,0.755
z10,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0.000
z11,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.000,0.981
z12,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.846,1.000

In [ ]:
upward = distillation(rank_credibility_comprehensiv, False, beta=0.4)
upward

1               [S7]
2               [S4]
3               [S5]
4               [S2]
5           [S1, S9]
6           [S3, S6]
7               [S8]
8    [z10, z11, z12]
dtype: object

In [ ]:
downward = distillation(rank_credibility_comprehensiv, True, beta=0.4)
downward

7            [S4, S7]
6                [S5]
5    [S1, S2, S3, S6]
4                [S9]
3          [z11, z12]
2                [S8]
1               [z10]
dtype: object

In [ ]:
ascending = order_to_outranking_matrix(upward)

In [ ]:
descending = order_to_outranking_matrix(downward)

In [ ]:
final = final_ranking_matrix(descending, ascending).round()
final

     S1  S2  S3  S4  S5  S6  S7  S8  S9  z10  z11  z12
S1    1   0   1   0   0   1   0   1   1    1    1    1
S2    1   1   1   0   0   1   0   1   1    1    1    1
S3    0   0   1   0   0   1   0   1   0    1    1    1
S4    1   1   1   1   1   1   0   1   1    1    1    1
S5    1   1   1   0   1   1   0   1   1    1    1    1
S6    0   0   1   0   0   1   0   1   0    1    1    1
S7    1   1   1   1   1   1   1   1   1    1    1    1
S8    0   0   0   0   0   0   0   1   0    1    0    0
S9    0   0   0   0   0   0   0   1   1    1    1    1
z10   0   0   0   0   0   0   0   0   0    1    0    0
z11   0   0   0   0   0   0   0   0   0    1    1    1
z12   0   0   0   0   0   0   0   0   0    1    1    1

In [ ]:
rank = ranks(final)
rank

1              [S7]
2              [S4]
3              [S5]
4              [S2]
5              [S1]
6      [S3, S6, S9]
7    [S8, z11, z12]
8             [z10]
dtype: object

In [ ]:
median = median_order(rank, downward, upward)
median

1           [S7]
2           [S4]
3           [S5]
4           [S2]
5           [S1]
6           [S9]
7       [S3, S6]
8           [S8]
9     [z11, z12]
10         [z10]
dtype: object